---
abstract: 'Simple TCP-based MPRPC client/server'
author:
  - 'Tokuhiro Matsuno <tokuhirom@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.98
  Test::TCP: 0.11
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.03'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-MPRPC
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0.13
  AnyEvent: 5.261
  Data::MessagePack: 0.34
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.13
